AWSTemplateFormatVersion: '2010-09-09'
Description: ALB with WAF protection for PHP Laravel application

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for ALB
  
  ALBSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ALB Security Group ID
  
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Public subnets for ALB (minimum 2)
  
  ResourcesEC2InstanceId:
    Type: AWS::EC2::Instance::Id
    Description: EC2 instance for resources subdomain
  
  ResourcesHostnames:
    Type: CommaDelimitedList
    Description: Hostnames for resources target group (e.g., resources.company.com,www.resources.company.com)
    Default: resources.company.com,www.resources.company.com
  
  CreateHTTPSListener:
    Type: String
    Description: Create HTTPS listener (requires at least one ACM certificate later)
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  
  InitialACMCertificateArn:
    Type: String
    Description: ACM Certificate ARN for HTTPS listener (required if CreateHTTPSListener is true)
    Default: ''

Conditions:
  HasHTTPSListener: !Equals [!Ref CreateHTTPSListener, 'true']

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref ALBSecurityGroupId

  ResourcesTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckEnabled: true
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Targets:
        - Id: !Ref ResourcesEC2InstanceId

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 404
            ContentType: text/plain
            MessageBody: Not Found

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: HasHTTPSListener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref InitialACMCertificateArn
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 404
            ContentType: text/plain
            MessageBody: Not Found

  ResourcesListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPListener
      Priority: 1
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values: !Ref ResourcesHostnames
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ResourcesTargetGroup

  ResourcesHTTPSListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: HasHTTPSListener
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 1
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values: !Ref ResourcesHostnames
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ResourcesTargetGroup

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CommonRuleSetMetric
        
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: KnownBadInputsMetric
        
        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 3
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SQLiRuleSetMetric
        
        - Name: AWSManagedRulesPHPRuleSet
          Priority: 4
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesPHPRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: PHPRuleSetMetric
        
        - Name: BlockEncodedPathTraversal
          Priority: 5
          Statement:
            OrStatement:
              Statements:
                - ByteMatchStatement:
                    SearchString: '%2e'
                    FieldToMatch:
                      UriPath: {}
                    TextTransformations:
                      - Priority: 0
                        Type: LOWERCASE
                    PositionalConstraint: CONTAINS
                - ByteMatchStatement:
                    SearchString: 'cgi-bin'
                    FieldToMatch:
                      UriPath: {}
                    TextTransformations:
                      - Priority: 0
                        Type: LOWERCASE
                    PositionalConstraint: CONTAINS
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: EncodedPathTraversalMetric
        
        - Name: RateLimitRule
          Priority: 6
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitMetric
      
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: WebACLMetric

  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Ref ApplicationLoadBalancer
      WebACLArn: !GetAtt WebACL.Arn

Outputs:
  LoadBalancerDNS:
    Description: ALB DNS Name
    Value: !GetAtt ApplicationLoadBalancer.DNSName
  
  LoadBalancerArn:
    Description: ALB ARN
    Value: !Ref ApplicationLoadBalancer
  
  HTTPListenerArn:
    Description: HTTP Listener ARN
    Value: !Ref HTTPListener
  
  HTTPSListenerArn:
    Description: HTTPS Listener ARN
    Condition: HasHTTPSListener
    Value: !Ref HTTPSListener
  
  ResourcesTargetGroupArn:
    Description: Resources Target Group ARN
    Value: !Ref ResourcesTargetGroup
  
  WebACLArn:
    Description: WAF Web ACL ARN
    Value: !GetAtt WebACL.Arn
